onboarding = false

[theme]
name = "dracula"

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_scope = "all"

[keys]
prefix = "ctrl+a"
previous_workspace = "ctrl+k"
next_workspace = "ctrl+j"

